[build-system]
requires = ["uv_build>=0.12.17,<1.0.0"]
build-backend = "uv_build"

[project]
name = "mediaferry"
version = "0.3.0"
authors = [
    {name = "DigitalDragon"}
]
description = "yt-dlp download management tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "internetarchive>=5.0.3",
    "dataclasses-json",
    "yt-dlp>=2025.12.8",
    "humanize"
]

[project.scripts]
mediaferry = "mediaferry.main:main"

[project.urls]
repository = "https://github.com/DigitalDwagon/MediaFerry"

[tool.uv.build-backend]
module-name = ["mediaferry"]
module-root = ""